module : cnn.feature_extraction.FeatureExtraction
model : cnn.OneHeadResNet50Model
data_root : /mnt/polyaxon/data1
dataset : cholec80_feature_extract.Cholec80FeatureExtract
data_split : 1 # for 5-Fold validation; can take values {1, 2, 3, 4, 5}
out_features : 7 # number of phases/tools
input_height : 224 # height of each frame
input_width : 224 # width of each frame
batch_size : 1000
fps_sampling : 1
fps_sampling_test : 1
learning_rate : 0.0005
dataset_mode : vid_multilabel
early_stopping_metric : val_acc_phase
pretrained : True
save_top_k : 1
max_epochs : 30 # 30
min_epochs : 12 # 20
num_tasks : 1
num_sanity_val_steps : 4
test_extract : True
#accelerator: ddp_spawn
num_workers : 10
gpus : ['0'] # use one of the available GPUs # all available -1
#resume_from_checkpoint : logs/201103-000243_FeatureExtraction_Cholec80FeatureExtract_cnn_TwoHeadResNet50Model/checkpoints/201103-000243_FeatureExtraction_Cholec80FeatureExtract_cnn_TwoHeadResNet50Model-epoch=10-val_acc_phase=0.83.ckpt

